repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: "Format Code with cargo fmt"
        entry: "cargo fmt -- --check"
        language: system
        types: [rust]

      - id: cargo-clippy
        name: "Lint Code with cargo clippy"
        entry: "cargo clippy -- -D warnings"
        language: system  # changed to "system"
        types: [rust]
        pass_filenames: false

      - id: cargo-test
        name: "Run Tests with cargo test"
        entry: "cargo test"
        language: system
        types: [rust]
        pass_filenames: false